# -*- coding: utf-8 -*-
"""Vendas - Analise de Churn (Evasão)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmEBS9keMOQjGbMovxtb145GmySYpk8i
"""

import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# String que contém os dados simulados
dados_churn_str = """
ID_Cliente,Tempo_Contrato_Meses,Valor_Mensal_R,Uso_Suporte_Tecnico,Promocoes_Recebidas,Churn
C01,12,75.00,2,0,0
C02,5,95.00,5,1,1
C03,36,60.50,1,0,0
C04,18,80.00,0,0,0
C05,8,110.00,4,2,1
C06,48,55.00,0,0,0
C07,2,120.00,6,1,1
C08,24,70.00,1,0,0
C09,15,105.00,3,1,1
C10,60,50.00,0,0,0
C11,1,130.00,7,2,1
C12,30,65.00,1,0,0
C13,10,100.00,4,1,1
C14,40,60.00,0,0,0
C15,3,115.00,5,2,1
"""
df_churn = pd.read_csv(StringIO(dados_churn_str))

# Definição de Features (X) e Target (y)
X = df_churn.drop(['ID_Cliente', 'Churn'], axis=1)
y = df_churn['Churn'] # 0 = Não Evadiu, 1 = Evadiu

# Divisão em Treinamento e Teste (70%/30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("--- DataFrame e Separação de Dados Concluídos ---")
print(f"Número de amostras para Treinamento: {len(X_train)}")

# Treinamento do Modelo
model_churn = LogisticRegression(random_state=42, solver='liblinear')
model_churn.fit(X_train, y_train)

print("--- Treinamento do Modelo de Regressão Logística Concluído! ✅ ---")

# Previsão no Conjunto de Teste
y_pred = model_churn.predict(X_test)

# Avaliação Inicial
acuracia = accuracy_score(y_test, y_pred)
matriz = confusion_matrix(y_test, y_pred)
relatorio = classification_report(y_test, y_pred, zero_division=0)

print(f"\n--- Avaliação no Conjunto de Teste ---")
print(f"Acurácia Geral: {acuracia:.2f}")
print("\nMatriz de Confusão:")
print(matriz)
print("\nRelatório de Classificação:")
print(relatorio)

# Coeficientes do Modelo: o impacto de cada feature na chance de evasão
coeficientes = pd.DataFrame({'Feature': X.columns, 'Impacto': model_churn.coef_[0]})
coeficientes['Impacto_Abs'] = np.abs(coeficientes['Impacto'])
coeficientes = coeficientes.sort_values(by='Impacto_Abs', ascending=False)

print("\n--- Impacto das Features na Evasão (Coefficients) ---")
print(coeficientes[['Feature', 'Impacto']].round(4))

# Nova Cliente para Previsão (Exemplo de Ação Preventiva)
novo_cliente = pd.DataFrame({
    'Tempo_Contrato_Meses': [6], # Pouco tempo
    'Valor_Mensal_R': [100.00], # Gasto alto
    'Uso_Suporte_Tecnico': [5], # Alto uso de suporte
    'Promocoes_Recebidas': [0] # Nenhuma promoção
})

# Previsão da Probabilidade de Evasão (Ação Preventiva)
probabilidade_churn = model_churn.predict_proba(novo_cliente)[:, 1]

print("\n--- Ação Preventiva: Previsão para Novo Cliente ---")
print(f"Probabilidade de Evasão (Churn): {probabilidade_churn[0]:.2f}")

# Regra de Negócio: Se Probabilidade > 0.60, enviar Oferta de Retenção personalizada.
if probabilidade_churn[0] > 0.60:
    print("\nRECOMENDAÇÃO: ALTO RISCO DE EVASÃO. Enviar Estratégia de Retenção Personalizada (Promoção ou Suporte Extra).")
else:
    print("\nRECOMENDAÇÃO: RISCO BAIXO. Monitorar.")